name: react-build-workflow
run-name: ${{ github.actor }} is building react
on: [push]
jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
      - uses: @actions/checkout@v3
      - uses: @actions/node-setup@v3
        with:
          node-version: "14"
      - name: Move to Directory
        run: cd ./frontend/fitjournal
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
