name: Build React App

on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend/fitjournal

      - name: Build React App
        run: npm run build
        working-directory: ./frontend/fitjournal

      - name: Deploy Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./frontend/fitjournal/build

      - name: Save Build Artifacts
        if: always()
        run: |
          mkdir -p $GITHUB_WORKSPACE/build
          mv $RUNNER_TEMP/build-artifact $GITHUB_WORKSPACE/build
